# -*- coding: utf-8 -*-
"""FizzBuzz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v4WfGJyjEqp9YmavOag6aUm940tBBTyw
"""

# Have this code run for any start and finish values

def FizzBuzz(start, finish):
    outlist = []
    for i in range(start, finish + 1):
        if i % 3 == 0 and i % 5 == 0:
            outlist.append("fizzbuzz")
        elif i % 3 == 0:
            outlist.append("fizz")
        elif i % 5 == 0:
            outlist.append("buzz")
        else:
            outlist.append(i)
    print(outlist)
    return outlist

# Test the function with start=1 and finish=100
result=FizzBuzz(1,100)
result