# -*- coding: utf-8 -*-
"""getBondPrice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W6pawuiywrLWiteWuk3w1bVQCkwMOc11
"""

def getBondPrice(y, face, couponRate, m, ppy=1):

    # Calculate the periodic interest rate
    r = y / ppy

    # Number of periods
    n = m * ppy

    c = (couponRate * face) / ppy

    pv_coupons = c * sum([(1 / (1 + r) ** t) for t in range(1, n + 1)])
    pv_face = face / (1 + r) ** n
    bondPrice = pv_coupons + pv_face

    return bondPrice

# Test values
y = 0.03
face = 2000000
couponRate = 0.04
m = 10
ppy_1 = 1
ppy_2 = 2


bond_price_annual = getBondPrice(y, face, couponRate, m, ppy_1)
bond_price_semi_annual = getBondPrice(y, face, couponRate, m, ppy_2)

print(f"Bond Price with Annual Payments: ${bond_price_annual:,.2f}")
print(f"Bond Price with Semi-Annual Payments: ${bond_price_semi_annual:,.2f}")