# -*- coding: utf-8 -*-
"""getBondPrice_E.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12fNhLngvB51YMKItNTLdU6kiYqKVnurw
"""

def getBondPrice_E(face, couponRate, yc):
    coupon = face * couponRate
    maturity = len(yc)

    bondPrice = sum(coupon / ((1 + yc[t]) ** (t + 1)) for t in range(maturity))
    bondPrice += face / ((1 + yc[-1]) ** maturity)

    return round(bondPrice, 2)

# Test values
yc = [0.010, 0.015, 0.020, 0.025, 0.030]
face = 2000000
couponRate = 0.04


bond_price = getBondPrice_E(face, couponRate, yc)
print("Bond Price: $", round(bond_price, 2))