# -*- coding: utf-8 -*-
"""getBondPrice_Z.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LqN-CHR5QE7Ryhqj8M5KmypHm_b6pJoz
"""

def getBondPrice_Z(face, couponRate, times, yc):
    coupon = face * couponRate


    bondPrice = sum(coupon / ((1 + r) ** t) for t, r in zip(times, yc))


    bondPrice += face / ((1 + yc[-1]) ** times[-1])

    return round(bondPrice, 2)

# Test values
yc = [0.010, 0.015, 0.020, 0.025, 0.030]
times = [1, 1.5, 3, 4, 7]
face = 2000000
couponRate = 0.04


bond_price = getBondPrice_Z(face, couponRate, times, yc)
print("Bond Price: $", bond_price)