# -*- coding: utf-8 -*-
"""WhoamI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1topC6FUEEthHLJYcSrdLzF-Hk4xMlW35
"""

def WhoAmI():
   return('djr2132')